version: "3.3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    command: --default-authentication-plugin=mysql_native_password --ft_min_word_len=1
    volumes:
      - opencart-data:/var/lib/mysql
      - ./mysql/opencart.sql:/opencart.sql
      - ./mysql/setup.sql:/setup.sql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
volumes:
  opencart-data: